lint.ignore = ["E203"]
exclude = ["__pycache__", ".old", ".venv", "build", "dist", "setup.py"]
lint.extend-select = [
    "F",        # Pyflakes rules
    "W",        # PyCodeStyle warnings
        # "E",        # PyCodeStyle errors
    "I",        # Sort imports properly
        # "UP",       # Warn if certain things can changed due to newer Python versions
    "C4",       # Catch incorrect use of comprehensions, dict, list, etc
    "FA",       # Enforce from __future__ import annotations
    "ISC",      # Good use of string concatenation
    "ICN",      # Use common import conventions
    "RET",      # Good return practices
        # "SIM",      # Common simplification rules
    "TID",      # Some good import practices
    "PTH",      # Use pathlib instead of os.path
    "TD",       # Be diligent with TODO comments
    "A",        # detect shadowed builtins
        # "BLE",      # disallow catch-all exceptions
    "COM",      # enforce trailing comma rules
    "DTZ",      # require strict timezone manipulation with datetime
    "FBT",      # detect boolean traps
    "N",        # enforce naming conventions, e.g. ClassName vs function_name
]

[lint.per-file-ignores]
"tests/*" = ["E402", "I001", "FBT003", "F401"]
